name: Deploy to Staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 128.0.0.1 >> ~/.ssh/known_hosts

      - name: SSH into server and deploy
        run: |
          ssh -i ~/.ssh/id_rsa root@128.0.0.1 << 'EOF'
            cd deploy-monorepo/
            git pull
            pnpm install
            pnpm run build
            pm2 restart web-server
            pm2 restart http-server
            pm2 restart ws-server
          EOF
